🧱 Butão de adicionar despesas
AIWASS23/cashome pull request #5
Opened 2022-11-29 18:28 UTC by AIWASS23

2022-11-30 14:29 UTC, christian-paulo approved these changes, later dismissed

2022-11-30 15:19 UTC, BeatrizLdS requested changes

2022-11-30 15:19 UTC, BeatrizLdS commented on Cashome/Views/HomeScreen.swift
> +            addButtonExpense.centerXAnchor.constraint(equalTo: centerXAnchor, constant: 160),
É melhor definir a a lateral direita (trailingAnchor), pois esse valor de 160 é muito grande e isso pode ser um problema em telas menores.

Pode fazer assim:
titleExpense.trailingAnchor.constraint(equalTo: self.traillingAnchor, constant: -17)

Benefícios: É mais seguro no posicionamento em diferentes telas.

2022-11-30 15:19 UTC, BeatrizLdS commented on Cashome/Views/HomeScreen.swift
> +            addButtonExpense.heightAnchor.constraint(equalToConstant: 60)
Talvez seja interessante tentar aumentar um pouco esse valor. 
Dá para rodar no celular e verificar se essa área de touch, para clicar no botão, está pequena.

2022-11-30 17:05 UTC, AIWASS23 commented on Cashome/Views/HomeScreen.swift
> +            addButtonExpense.centerXAnchor.constraint(equalTo: centerXAnchor, constant: 160),
ajustes de constraints feito

2022-11-30 17:07 UTC, AIWASS23 commented on Cashome/Views/HomeScreen.swift
> +            addButtonExpense.heightAnchor.constraint(equalToConstant: 60)
Conversando com a Elis, ela me falou que a superfície de touch do botão tem que ser referente a area dele. ela sugeriu que diminuísse essa área para o tamanho exato do botão

2022-12-01 11:19 UTC, BeatrizLdS approved these changes

2022-12-01 11:21 UTC, BeatrizLdS approved these changes

2022-12-01 11:25 UTC, rainarodrigues approved these changes

2022-12-01 11:25 UTC, merged