🧱 Label despesas
AIWASS23/cashome pull request #7
Opened 2022-11-30 12:50 UTC by AIWASS23

Refatorar label para reaproveitamento de código

2022-11-30 14:39 UTC, christian-paulo requested changes
tira essas coisas

2022-11-30 14:39 UTC, christian-paulo commented on Cashome/Views/HomeScreen.swift
> +
APAGAR ESSE MONTE DE ESPAÇO

2022-11-30 14:39 UTC, christian-paulo commented on Cashome/Views/HomeScreen.swift
> +
MUITO ESPAÇO

2022-11-30 14:53 UTC, christian-paulo approved these changes, later dismissed

2022-11-30 15:12 UTC, BeatrizLdS requested changes

2022-11-30 15:12 UTC, BeatrizLdS commented on Cashome/Views/HomeScreen.swift
> +            titleExpense.centerXAnchor.constraint(equalTo: centerXAnchor, constant: -110),
É melhor definir a a lateral esquerda, pois esse valor 110 é muito grande e isso pode ser um problema em telas menores.

Pode fazer assim:
`titleExpense.leadingAnchor.constraint(equalTo: self.leadingAnchor, constant: 17)`

Benefícios: É mais seguro no posicionamento em diferentes telas.

2022-11-30 16:51 UTC, AIWASS23 commented on Cashome/Views/HomeScreen.swift
> +            titleExpense.centerXAnchor.constraint(equalTo: centerXAnchor, constant: -110),
ajuste de code review feito

2022-12-01 11:20 UTC, BeatrizLdS submitted a review, later dismissed

2022-12-01 11:26 UTC, rainarodrigues submitted a review, later dismissed

2022-12-01 11:26 UTC, christian-paulo submitted a review, later dismissed

2022-12-01 11:43 UTC, christian-paulo approved these changes

2022-12-01 11:43 UTC, BeatrizLdS approved these changes

2022-12-01 11:44 UTC, merged